"""
babel.compiler.adapters.ag2_adapter
------------------------------------
Compiles a Babel spec into an AG2-compatible tool binding.

Output layout:
    dist/ag2/<tool_id>/
        tool.py       — importable module exposing TOOL_FUNCTION + TOOL_SCHEMA
        schema.json   — OpenAI-compatible tool schema (for reference / E3 use)
        meta.json     — spec metadata cache

BabelRuntime.load(tool_id, target="ag2") dynamically imports tool.py and
returns the (TOOL_FUNCTION, TOOL_SCHEMA) pair.

Usage:
    adapter = AG2Adapter()
    out_dir = adapter.compile_from_file(Path("tools/weather/spec.yaml"), Path("dist"))
    # → dist/ag2/com.aria.tools.weather/
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

from babel.compiler.base import BabelAdapter


class AG2Adapter(BabelAdapter):
    """Compiles a Babel spec into an AG2-native tool module."""

    @property
    def target_name(self) -> str:
        return "ag2"

    def compile(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        output_dir: Path,
    ) -> Path:
        """Compile spec + impl into dist/ag2/<tool_id>/.

        Returns:
            Path to the compiled output directory.
        """
        tool_id = spec["id"]
        out_dir = output_dir / "ag2" / tool_id
        out_dir.mkdir(parents=True, exist_ok=True)

        tool_schema = self._build_openai_tool_schema(spec)
        fn_signature = self._build_python_signature(spec)
        fn_name = spec["id"].split(".")[-1]

        # Build kwarg pass-through from the function signature to impl_module.run()
        kwarg_names = [p["name"] for p in spec["interface"]["inputs"]]
        kwargs_str = ", ".join(f"{n}={n}" for n in kwarg_names)

        # Generate tool.py source
        tool_py = self._render_tool_py(
            spec=spec,
            impl_path=impl_path.resolve(),
            fn_name=fn_name,
            fn_signature=fn_signature,
            kwargs_str=kwargs_str,
            tool_schema=tool_schema,
        )

        (out_dir / "tool.py").write_text(tool_py)
        (out_dir / "schema.json").write_text(
            json.dumps(tool_schema, indent=2)
        )
        (out_dir / "meta.json").write_text(
            json.dumps(
                {
                    "tool_id": tool_id,
                    "name": spec["name"],
                    "description": spec["description"],
                    "babel_version": spec["babel_version"],
                    "impl_path": str(impl_path.resolve()),
                    "targets": spec.get("targets", ["ag2"]),
                    "metadata": spec.get("metadata", {}),
                },
                indent=2,
            )
        )

        return out_dir

    # ------------------------------------------------------------------

    def _render_tool_py(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        fn_name: str,
        fn_signature: str,
        kwargs_str: str,
        tool_schema: dict[str, Any],
    ) -> str:
        """Render the tool.py source that BabelRuntime will import."""

        timeout = spec.get("execution", {}).get("timeout", 30)
        retries = spec.get("execution", {}).get("retries", 0)
        description = spec["description"]
        tool_id = spec["id"]
        schema_json = json.dumps(tool_schema, indent=4)

        # Build default values block for optional params
        defaults_lines = []
        for param in spec["interface"]["inputs"]:
            if "default" in param and param.get("required", True) is False:
                pass  # handled in signature
        defaults_block = "\n".join(defaults_lines)

        return textwrap.dedent(f'''\
            """
            Auto-generated AG2 tool binding for: {tool_id}
            Generated by Babel Compiler v1.0 — AG2 Adapter
            DO NOT EDIT — regenerate with: babel compile <spec> --target ag2
            """

            from __future__ import annotations
            import importlib.util
            import sys
            import time
            from pathlib import Path
            from typing import Any

            # ---------------------------------------------------------------------------
            # Load implementation module from absolute path baked in at compile time
            # ---------------------------------------------------------------------------
            _IMPL_PATH = Path(r"{impl_path}")
            _TIMEOUT = {timeout}
            _RETRIES = {retries}

            def _load_impl():
                spec = importlib.util.spec_from_file_location("_babel_impl_{fn_name}", _IMPL_PATH)
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                return mod

            _impl = _load_impl()

            # ---------------------------------------------------------------------------
            # AG2-compatible tool function
            # ---------------------------------------------------------------------------

            def {fn_signature}
                """
                {description}

                Tool ID: {tool_id}
                Timeout: {timeout}s | Retries: {retries}
                """
                last_exc = None
                for attempt in range(_RETRIES + 1):
                    try:
                        result = _impl.run({kwargs_str})
                        return result
                    except Exception as exc:
                        last_exc = exc
                        if attempt < _RETRIES:
                            time.sleep(0.5 * (attempt + 1))
                return {{"error": str(last_exc), "code": 500}}


            # ---------------------------------------------------------------------------
            # Exports consumed by BabelRuntime.load()
            # ---------------------------------------------------------------------------
            TOOL_FUNCTION = {fn_name}
            TOOL_ID = "{tool_id}"
            TOOL_SCHEMA = {schema_json}
        ''')
