"""
babel.compiler.adapters.langchain_adapter
------------------------------------------
Compiles a Babel spec into a LangChain native tool binding.

Output layout:
    dist/langchain/<tool_id>/
        tool.py       — exposes TOOL_FUNCTION, TOOL_OBJECT (StructuredTool), TOOL_SCHEMA
        schema.json   — OpenAI-compatible schema
        meta.json     — metadata cache

BabelRuntime.load(tool_id, target="langchain") imports tool.py and returns:
    {
        "name":        str,
        "description": str,
        "function":    callable,
        "schema":      dict,
        "tool_object": StructuredTool   ← pass directly to llm.bind_tools([...])
    }

Usage:
    adapter = LangChainAdapter()
    out_dir = adapter.compile_from_file(Path("tools/weather/spec.yaml"), Path("dist"))
    # → dist/langchain/com.aria.tools.weather/
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from babel.compiler.base import BabelAdapter


class LangChainAdapter(BabelAdapter):
    """Compiles a Babel spec into a LangChain StructuredTool binding."""

    @property
    def target_name(self) -> str:
        return "langchain"

    def compile(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        output_dir: Path,
    ) -> Path:
        """Compile spec + impl into dist/langchain/<tool_id>/."""
        tool_id = spec["id"]
        out_dir = output_dir / "langchain" / tool_id
        out_dir.mkdir(parents=True, exist_ok=True)

        tool_schema = self._build_openai_tool_schema(spec)
        fn_signature = self._build_python_signature(spec)
        fn_name = spec["id"].split(".")[-1]
        kwarg_names = [p["name"] for p in spec["interface"]["inputs"]]
        kwargs_str = ", ".join(f"{n}={n}" for n in kwarg_names)

        tool_py = self._render_tool_py(spec, impl_path.resolve(), fn_name, fn_signature, kwargs_str, tool_schema)

        (out_dir / "tool.py").write_text(tool_py)
        (out_dir / "schema.json").write_text(json.dumps(tool_schema, indent=2))
        (out_dir / "meta.json").write_text(
            json.dumps({"tool_id": tool_id, "name": spec["name"],
                        "description": spec["description"],
                        "target": "langchain", "metadata": spec.get("metadata", {})}, indent=2)
        )
        return out_dir

    def _render_tool_py(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        fn_name: str,
        fn_signature: str,
        kwargs_str: str,
        tool_schema: dict[str, Any],
    ) -> str:
        tool_id = spec["id"]
        description = spec["description"].replace('"', '\\"')
        timeout = spec.get("execution", {}).get("timeout", 30)
        retries = spec.get("execution", {}).get("retries", 0)
        schema_json = json.dumps(tool_schema, indent=4)

        lines = [
            '"""',
            f"Auto-generated LangChain tool binding for: {tool_id}",
            "Generated by Babel Compiler v1.0 — LangChain Adapter",
            "DO NOT EDIT — regenerate with: babel compile <spec> --target langchain",
            '"""',
            "",
            "from __future__ import annotations",
            "import importlib.util",
            "import time",
            "from pathlib import Path",
            "",
            f"_IMPL_PATH = Path(r'{impl_path}')",
            f"_TIMEOUT = {timeout}",
            f"_RETRIES = {retries}",
            "",
            "",
            "def _load_impl():",
            f'    _spec = importlib.util.spec_from_file_location("_babel_impl_{fn_name}", _IMPL_PATH)',
            "    _mod = importlib.util.module_from_spec(_spec)",
            "    _spec.loader.exec_module(_mod)",
            "    return _mod",
            "",
            "",
            "_impl = _load_impl()",
            "",
            "",
            "# -----------------------------------------------------------------------",
            "# LangChain compatible tool function",
            "# -----------------------------------------------------------------------",
            "",
            fn_signature,
            f'    """{description}"""',
            "    last_exc = None",
            f"    for attempt in range(_RETRIES + 1):",
            "        try:",
            f"            return _impl.run({kwargs_str})",
            "        except Exception as exc:",
            "            last_exc = exc",
            "            if attempt < _RETRIES:",
            "                time.sleep(0.5 * (attempt + 1))",
            '    return {"error": str(last_exc), "code": 500}',
            "",
            "",
            "# -----------------------------------------------------------------------",
            "# Build LangChain StructuredTool — ready to pass to llm.bind_tools([...])",
            "# -----------------------------------------------------------------------",
            "",
            "def _build_tool_object():",
            "    try:",
            "        from langchain_core.tools import StructuredTool",
            f"        return StructuredTool.from_function(",
            f"            func={fn_name},",
            f"            name={repr(fn_name)},",
            f"            description={repr(spec['description'])},",
            "        )",
            "    except ImportError:",
            "        return None",
            "",
            "",
            "# -----------------------------------------------------------------------",
            "# Exports",
            "# -----------------------------------------------------------------------",
            f"TOOL_FUNCTION = {fn_name}",
            f'TOOL_ID = "{tool_id}"',
            f"TOOL_SCHEMA = {schema_json}",
            "TOOL_OBJECT = _build_tool_object()   # langchain StructuredTool | None",
            "",
        ]
        return "\n".join(lines)
