"""
babel.compiler.adapters.raw_python_adapter
-------------------------------------------
Compiles a Babel spec into a standalone Python callable + JSON schema.

No AG2 dependency. Useful for testing tools in isolation or calling them
from scripts without the full AG2 runtime.

Output layout:
    dist/raw_python/<tool_id>/
        tool.py       — importable module with TOOL_FUNCTION callable
        schema.json   — OpenAI-compatible function schema
        meta.json     — metadata

Usage:
    adapter = RawPythonAdapter()
    out_dir = adapter.compile_from_file(Path("tools/weather/spec.yaml"), Path("dist"))
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from babel_registry.compiler.base import BabelAdapter


class RawPythonAdapter(BabelAdapter):
    """Compiles a Babel spec into a standalone Python callable."""

    @property
    def target_name(self) -> str:
        return "raw_python"

    def compile(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        output_dir: Path,
    ) -> Path:
        """Compile spec + impl into dist/raw_python/<tool_id>/.

        Returns:
            Path to the compiled output directory.
        """
        tool_id = spec["id"]
        out_dir = output_dir / "raw_python" / tool_id
        out_dir.mkdir(parents=True, exist_ok=True)

        tool_schema = self._build_openai_tool_schema(spec)
        fn_signature = self._build_python_signature(spec)
        fn_name = spec["id"].split(".")[-1]
        kwarg_names = [p["name"] for p in spec["interface"]["inputs"]]
        kwargs_str = ", ".join(f"{n}={n}" for n in kwarg_names)

        tool_py = self._render_tool_py(
            spec=spec,
            impl_path=impl_path.resolve(),
            fn_name=fn_name,
            fn_signature=fn_signature,
            kwargs_str=kwargs_str,
        )

        (out_dir / "tool.py").write_text(tool_py)
        (out_dir / "schema.json").write_text(json.dumps(tool_schema, indent=2))
        (out_dir / "meta.json").write_text(
            json.dumps(
                {
                    "tool_id": tool_id,
                    "name": spec["name"],
                    "description": spec["description"],
                    "impl_path": str(impl_path.resolve()),
                    "metadata": spec.get("metadata", {}),
                },
                indent=2,
            )
        )

        return out_dir

    # ------------------------------------------------------------------

    def _render_tool_py(
        self,
        spec: dict[str, Any],
        impl_path: Path,
        fn_name: str,
        fn_signature: str,
        kwargs_str: str,
    ) -> str:
        tool_id = spec["id"]
        description = spec["description"].replace('"', '\\"')
        timeout = spec.get("execution", {}).get("timeout", 30)
        retries = spec.get("execution", {}).get("retries", 0)

        lines = [
            '"""',
            f"Auto-generated raw Python binding for: {tool_id}",
            "Generated by Babel Compiler v1.0 — RawPython Adapter",
            "DO NOT EDIT — regenerate with: babel compile <spec> --target raw_python",
            '"""',
            "",
            "from __future__ import annotations",
            "import importlib.util",
            "import time",
            "from pathlib import Path",
            "",
            f"_IMPL_PATH = Path(r'{impl_path}')",
            f"_TIMEOUT = {timeout}",
            f"_RETRIES = {retries}",
            "",
            "",
            "def _load_impl():",
            f'    _spec = importlib.util.spec_from_file_location("_babel_impl_{fn_name}", _IMPL_PATH)',
            "    _mod = importlib.util.module_from_spec(_spec)",
            "    _spec.loader.exec_module(_mod)",
            "    return _mod",
            "",
            "",
            "_impl = _load_impl()",
            "",
            "",
            # fn_signature already starts with "def"
            fn_signature,
            f'    """{description}"""',
            "    last_exc = None",
            f"    for attempt in range(_RETRIES + 1):",
            "        try:",
            f"            return _impl.run({kwargs_str})",
            "        except Exception as exc:",
            "            last_exc = exc",
            "            if attempt < _RETRIES:",
            "                time.sleep(0.5 * (attempt + 1))",
            '    return {"error": str(last_exc), "code": 500}',
            "",
            "",
            "# Exports",
            f"TOOL_FUNCTION = {fn_name}",
            f'TOOL_ID = "{tool_id}"',
            "",
        ]
        return "\n".join(lines)
