package store

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/openswarm/openswarm/internal/domain"
	"github.com/openswarm/openswarm/internal/store/db"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// Store provides PostgreSQL-backed persistence for the OpenSwarm control plane.
// All queries are generated by sqlc for type safety.
type Store struct {
	pool *pgxpool.Pool
	q    *db.Queries
}

// New connects to PostgreSQL and returns a ready Store.
func New(ctx context.Context, databaseURL string) (*Store, error) {
	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		return nil, fmt.Errorf("store: connect: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &Store{pool: pool, q: db.New(pool)}, nil
}

// Close releases the connection pool.
func (s *Store) Close() {
	s.pool.Close()
}

// Pool exposes the underlying pgxpool.Pool for direct use (e.g. transactions).
func (s *Store) Pool() *pgxpool.Pool {
	return s.pool
}

// ---------------------------------------------------------------------------
// Migrations
// ---------------------------------------------------------------------------

// RunMigrations reads embedded SQL files in lexicographic order and executes
// each one inside a transaction. Migrations containing the directive
// "-- no-transaction" on their first line are executed directly (required by
// PostgreSQL for commands like CREATE MATERIALIZED VIEW ... WITH DATA).
func (s *Store) RunMigrations(ctx context.Context) error {
	entries, err := fs.ReadDir(migrationFS, "migrations")
	if err != nil {
		return fmt.Errorf("store: read migrations dir: %w", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name() < entries[j].Name()
	})

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		data, err := migrationFS.ReadFile("migrations/" + entry.Name())
		if err != nil {
			return fmt.Errorf("store: read migration %s: %w", entry.Name(), err)
		}

		if bytes.Contains(data[:min(len(data), 100)], []byte("-- no-transaction")) {
			for _, stmt := range strings.Split(string(data), ";") {
				stmt = strings.TrimSpace(stmt)
				stripped := stripSQLComments(stmt)
				if stripped == "" {
					continue
				}
				if _, err := s.pool.Exec(ctx, stmt); err != nil {
					return fmt.Errorf("store: exec migration %s (no-tx): %w", entry.Name(), err)
				}
			}
			continue
		}

		tx, err := s.pool.Begin(ctx)
		if err != nil {
			return fmt.Errorf("store: begin tx for %s: %w", entry.Name(), err)
		}
		if _, err := tx.Exec(ctx, string(data)); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("store: exec migration %s: %w", entry.Name(), err)
		}
		if err := tx.Commit(ctx); err != nil {
			return fmt.Errorf("store: commit migration %s: %w", entry.Name(), err)
		}
	}
	return nil
}

func stripSQLComments(s string) string {
	var lines []string
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "--") {
			continue
		}
		lines = append(lines, trimmed)
	}
	return strings.Join(lines, "\n")
}

// ---------------------------------------------------------------------------
// Swarms (sqlc-backed)
// ---------------------------------------------------------------------------

func (s *Store) CreateSwarm(ctx context.Context, sw *domain.Swarm) error {
	specJSON, err := json.Marshal(sw.Spec)
	if err != nil {
		return fmt.Errorf("store: marshal swarm spec: %w", err)
	}
	row, err := s.q.CreateSwarm(ctx, db.CreateSwarmParams{
		Name:   sw.Name,
		Spec:   specJSON,
		Status: string(sw.Status),
	})
	if err != nil {
		return fmt.Errorf("store: create swarm: %w", err)
	}
	sw.ID = row.ID
	sw.CreatedAt = pgTime(row.CreatedAt)
	sw.UpdatedAt = pgTime(row.UpdatedAt)
	return nil
}

func (s *Store) ListSwarms(ctx context.Context) ([]domain.Swarm, error) {
	rows, err := s.q.ListSwarms(ctx)
	if err != nil {
		return nil, fmt.Errorf("store: list swarms: %w", err)
	}
	out := make([]domain.Swarm, 0, len(rows))
	for _, r := range rows {
		sw, err := swarmFromRow(r)
		if err != nil {
			return nil, err
		}
		out = append(out, sw)
	}
	return out, nil
}

func (s *Store) GetSwarmByName(ctx context.Context, name string) (*domain.Swarm, error) {
	r, err := s.q.GetSwarmByName(ctx, db.GetSwarmByNameParams{Name: name})
	if err != nil {
		return nil, fmt.Errorf("store: get swarm %q: %w", name, err)
	}
	sw, err := swarmFromRow(r)
	if err != nil {
		return nil, err
	}
	return &sw, nil
}

func (s *Store) DeleteSwarm(ctx context.Context, name string) error {
	// Cascade: delete tasks and agent_specs that reference this swarm first
	_, _ = s.pool.Exec(ctx, `DELETE FROM tasks WHERE swarm_id = (SELECT id FROM swarms WHERE name = $1)`, name)
	_, _ = s.pool.Exec(ctx, `DELETE FROM agent_specs WHERE swarm_id = (SELECT id FROM swarms WHERE name = $1)`, name)

	tag, err := s.q.DeleteSwarm(ctx, db.DeleteSwarmParams{Name: name})
	if err != nil {
		return fmt.Errorf("store: delete swarm %q: %w", name, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("store: swarm %q not found", name)
	}
	return nil
}

func (s *Store) UpdateSwarmStatus(ctx context.Context, name string, status domain.SwarmStatus) error {
	tag, err := s.q.UpdateSwarmStatus(ctx, db.UpdateSwarmStatusParams{
		Status: string(status),
		Name:   name,
	})
	if err != nil {
		return fmt.Errorf("store: update swarm status %q: %w", name, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("store: swarm %q not found", name)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Tasks (sqlc-backed)
// ---------------------------------------------------------------------------

func (s *Store) CreateTask(ctx context.Context, t *domain.Task) error {
	metaJSON, err := json.Marshal(t.Metadata)
	if err != nil {
		return fmt.Errorf("store: marshal task metadata: %w", err)
	}
	row, err := s.q.CreateTask(ctx, db.CreateTaskParams{
		SwarmName: t.SwarmName,
		AgentRole: t.AgentRole,
		Input:     t.Input,
		Status:    string(t.Status),
		Metadata:  metaJSON,
	})
	if err != nil {
		return fmt.Errorf("store: create task: %w", err)
	}
	t.ID = row.ID
	t.CreatedAt = pgTime(row.CreatedAt)
	return nil
}

func (s *Store) ListTasksBySwarm(ctx context.Context, swarmName string) ([]domain.Task, error) {
	rows, err := s.q.ListTasksBySwarm(ctx, db.ListTasksBySwarmParams{Name: swarmName})
	if err != nil {
		return nil, fmt.Errorf("store: list tasks for swarm %q: %w", swarmName, err)
	}
	out := make([]domain.Task, 0, len(rows))
	for _, r := range rows {
		out = append(out, taskFromListRow(r))
	}
	return out, nil
}

func (s *Store) GetTaskByID(ctx context.Context, id string) (*domain.Task, error) {
	r, err := s.q.GetTaskByID(ctx, db.GetTaskByIDParams{ID: id})
	if err != nil {
		return nil, fmt.Errorf("store: get task %q: %w", id, err)
	}
	t := taskFromGetRow(r)
	return &t, nil
}

func (s *Store) UpdateTaskStatus(ctx context.Context, id string, status domain.TaskStatus, assignedAgent string) error {
	if assignedAgent != "" {
		result, err := s.q.UpdateTaskStatus(ctx, db.UpdateTaskStatusParams{
			Status:          string(status),
			AssignedAgentID: pgtype.Text{String: assignedAgent, Valid: true},
			ID:              id,
		})
		if err != nil {
			return fmt.Errorf("store: update task status %q: %w", id, err)
		}
		if result.RowsAffected() == 0 {
			return fmt.Errorf("store: task %q not found", id)
		}
		return nil
	}
	result, err := s.q.UpdateTaskStatusOnly(ctx, db.UpdateTaskStatusOnlyParams{
		Status: string(status),
		ID:     id,
	})
	if err != nil {
		return fmt.Errorf("store: update task status %q: %w", id, err)
	}
	if result.RowsAffected() == 0 {
		return fmt.Errorf("store: task %q not found", id)
	}
	return nil
}

func (s *Store) UpdateTaskResult(ctx context.Context, id string, output string, tokensUsed int, costUSD float64, latencyMs int64, taskErr string) error {
	now := time.Now()
	errText := pgtype.Text{}
	if taskErr != "" {
		errText = pgtype.Text{String: taskErr, Valid: true}
	}
	result, err := s.q.UpdateTaskResult(ctx, db.UpdateTaskResultParams{
		Output:      pgtype.Text{String: output, Valid: output != ""},
		TokensUsed:  int32(tokensUsed),
		CostUsd:     costUSD,
		LatencyMs:   pgtype.Int4{Int32: int32(latencyMs), Valid: true},
		Error:       errText,
		CompletedAt: pgtype.Timestamptz{Time: now, Valid: true},
		ID:          id,
	})
	if err != nil {
		return fmt.Errorf("store: update task result %q: %w", id, err)
	}
	if result.RowsAffected() == 0 {
		return fmt.Errorf("store: task %q not found", id)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Policies (sqlc-backed)
// ---------------------------------------------------------------------------

func (s *Store) CreatePolicy(ctx context.Context, p *domain.Policy) error {
	specJSON, err := json.Marshal(p.Spec)
	if err != nil {
		return fmt.Errorf("store: marshal policy spec: %w", err)
	}
	row, err := s.q.CreatePolicy(ctx, db.CreatePolicyParams{
		Name: p.Name,
		Spec: specJSON,
	})
	if err != nil {
		return fmt.Errorf("store: create policy: %w", err)
	}
	p.ID = row.ID
	p.CreatedAt = pgTime(row.CreatedAt)
	return nil
}

func (s *Store) ListPolicies(ctx context.Context) ([]domain.Policy, error) {
	rows, err := s.q.ListPolicies(ctx)
	if err != nil {
		return nil, fmt.Errorf("store: list policies: %w", err)
	}
	out := make([]domain.Policy, 0, len(rows))
	for _, r := range rows {
		p, err := policyFromRow(r)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, nil
}

func (s *Store) GetPolicyByName(ctx context.Context, name string) (*domain.Policy, error) {
	r, err := s.q.GetPolicyByName(ctx, db.GetPolicyByNameParams{Name: name})
	if err != nil {
		return nil, fmt.Errorf("store: get policy %q: %w", name, err)
	}
	p, err := policyFromRow(r)
	if err != nil {
		return nil, err
	}
	return &p, nil
}

// ---------------------------------------------------------------------------
// Genomes (sqlc-backed)
// ---------------------------------------------------------------------------

// GenomeRow is a raw row from the genomes table, used to decouple the store
// from the genetics package types.
type GenomeRow struct {
	ID          string
	SwarmName   string
	AgentRole   string
	Generation  int
	ParentIDs   []string
	Active      bool
	GenesJSON   []byte
	FitnessJSON []byte
	CreatedAt   time.Time
}

func (s *Store) CreateGenome(ctx context.Context, id, swarmName, agentRole string, generation int, parentIDs []string, active bool, genesJSON []byte, fitnessJSON []byte) error {
	if err := s.q.CreateGenome(ctx, db.CreateGenomeParams{
		ID:         id,
		SwarmName:  swarmName,
		AgentRole:  agentRole,
		Generation: int32(generation),
		ParentIds:  parentIDs,
		Active:     active,
		Genes:      genesJSON,
		Fitness:    fitnessJSON,
	}); err != nil {
		return fmt.Errorf("store: create genome: %w", err)
	}
	return nil
}

func (s *Store) ListGenomesBySwarm(ctx context.Context, swarmName string) ([]GenomeRow, error) {
	rows, err := s.q.ListGenomesBySwarm(ctx, db.ListGenomesBySwarmParams{SwarmName: swarmName})
	if err != nil {
		return nil, fmt.Errorf("store: list genomes for swarm %q: %w", swarmName, err)
	}
	out := make([]GenomeRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, genomeFromListRow(r))
	}
	return out, nil
}

func (s *Store) GetGenomeByID(ctx context.Context, id string) (*GenomeRow, error) {
	r, err := s.q.GetGenomeByID(ctx, db.GetGenomeByIDParams{ID: id})
	if err != nil {
		return nil, fmt.Errorf("store: get genome %q: %w", id, err)
	}
	g := genomeFromGetRow(r)
	return &g, nil
}

func (s *Store) UpdateGenomeFitness(ctx context.Context, id string, fitnessJSON []byte) error {
	tag, err := s.q.UpdateGenomeFitness(ctx, db.UpdateGenomeFitnessParams{
		Fitness: fitnessJSON,
		ID:      id,
	})
	if err != nil {
		return fmt.Errorf("store: update genome fitness %q: %w", id, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("store: genome %q not found", id)
	}
	return nil
}

func (s *Store) DeactivateGenomes(ctx context.Context, swarmName, agentRole string) error {
	if err := s.q.DeactivateGenomes(ctx, db.DeactivateGenomesParams{
		SwarmName: swarmName,
		AgentRole: agentRole,
	}); err != nil {
		return fmt.Errorf("store: deactivate genomes for %s/%s: %w", swarmName, agentRole, err)
	}
	return nil
}

func (s *Store) ListActiveGenomesByRole(ctx context.Context, swarmName, agentRole string) ([]GenomeRow, error) {
	rows, err := s.q.ListActiveGenomesByRole(ctx, db.ListActiveGenomesByRoleParams{
		SwarmName: swarmName,
		AgentRole: agentRole,
	})
	if err != nil {
		return nil, fmt.Errorf("store: list active genomes for %s/%s: %w", swarmName, agentRole, err)
	}
	out := make([]GenomeRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, genomeFromActiveRow(r))
	}
	return out, nil
}

// ---------------------------------------------------------------------------
// Type conversion helpers (sqlc pgtype ↔ domain types)
// ---------------------------------------------------------------------------

func pgTime(t pgtype.Timestamptz) time.Time {
	if t.Valid {
		return t.Time
	}
	return time.Time{}
}

func pgTimePtr(t pgtype.Timestamptz) *time.Time {
	if t.Valid {
		return &t.Time
	}
	return nil
}

func pgText(t pgtype.Text) string {
	if t.Valid {
		return t.String
	}
	return ""
}

func pgInt4ToInt64(i pgtype.Int4) int64 {
	if i.Valid {
		return int64(i.Int32)
	}
	return 0
}

func swarmFromRow(r db.Swarm) (domain.Swarm, error) {
	var sw domain.Swarm
	sw.ID = r.ID
	sw.Name = r.Name
	sw.Status = domain.SwarmStatus(r.Status)
	sw.CreatedAt = pgTime(r.CreatedAt)
	sw.UpdatedAt = pgTime(r.UpdatedAt)
	if err := json.Unmarshal(r.Spec, &sw.Spec); err != nil {
		return sw, fmt.Errorf("store: unmarshal swarm spec: %w", err)
	}
	return sw, nil
}

func policyFromRow(r db.Policy) (domain.Policy, error) {
	var p domain.Policy
	p.ID = r.ID
	p.Name = r.Name
	p.CreatedAt = pgTime(r.CreatedAt)
	if err := json.Unmarshal(r.Spec, &p.Spec); err != nil {
		return p, fmt.Errorf("store: unmarshal policy spec: %w", err)
	}
	return p, nil
}

func taskFromListRow(r db.ListTasksBySwarmRow) domain.Task {
	t := domain.Task{
		ID:            r.ID,
		SwarmName:     r.SwarmName,
		AgentRole:     r.AgentRole,
		AssignedAgent: pgText(r.AssignedAgentID),
		Input:         r.Input,
		Output:        pgText(r.Output),
		Status:        domain.TaskStatus(r.Status),
		TokensUsed:    int(r.TokensUsed),
		CostUSD:       r.CostUsd,
		LatencyMs:     pgInt4ToInt64(r.LatencyMs),
		Error:         pgText(r.Error),
		TraceID:       pgText(r.TraceID),
		CreatedAt:     pgTime(r.CreatedAt),
		CompletedAt:   pgTimePtr(r.CompletedAt),
	}
	if r.Metadata != nil {
		_ = json.Unmarshal(r.Metadata, &t.Metadata)
	}
	return t
}

func taskFromGetRow(r db.GetTaskByIDRow) domain.Task {
	t := domain.Task{
		ID:            r.ID,
		SwarmName:     r.SwarmName,
		AgentRole:     r.AgentRole,
		AssignedAgent: pgText(r.AssignedAgentID),
		Input:         r.Input,
		Output:        pgText(r.Output),
		Status:        domain.TaskStatus(r.Status),
		TokensUsed:    int(r.TokensUsed),
		CostUSD:       r.CostUsd,
		LatencyMs:     pgInt4ToInt64(r.LatencyMs),
		Error:         pgText(r.Error),
		TraceID:       pgText(r.TraceID),
		CreatedAt:     pgTime(r.CreatedAt),
		CompletedAt:   pgTimePtr(r.CompletedAt),
	}
	if r.Metadata != nil {
		_ = json.Unmarshal(r.Metadata, &t.Metadata)
	}
	return t
}

func genomeFromListRow(r db.ListGenomesBySwarmRow) GenomeRow {
	return GenomeRow{
		ID:          r.ID,
		SwarmName:   r.SwarmName,
		AgentRole:   r.AgentRole,
		Generation:  int(r.Generation),
		ParentIDs:   r.ParentIds,
		Active:      r.Active,
		GenesJSON:   r.Genes,
		FitnessJSON: r.Fitness,
		CreatedAt:   pgTime(r.CreatedAt),
	}
}

func genomeFromGetRow(r db.GetGenomeByIDRow) GenomeRow {
	return GenomeRow{
		ID:          r.ID,
		SwarmName:   r.SwarmName,
		AgentRole:   r.AgentRole,
		Generation:  int(r.Generation),
		ParentIDs:   r.ParentIds,
		Active:      r.Active,
		GenesJSON:   r.Genes,
		FitnessJSON: r.Fitness,
		CreatedAt:   pgTime(r.CreatedAt),
	}
}

func genomeFromActiveRow(r db.ListActiveGenomesByRoleRow) GenomeRow {
	return GenomeRow{
		ID:          r.ID,
		SwarmName:   r.SwarmName,
		AgentRole:   r.AgentRole,
		Generation:  int(r.Generation),
		ParentIDs:   r.ParentIds,
		Active:      r.Active,
		GenesJSON:   r.Genes,
		FitnessJSON: r.Fitness,
		CreatedAt:   pgTime(r.CreatedAt),
	}
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

// GetSettings returns the platform settings for the given key ("global" for platform-wide).
func (s *Store) GetSettings(ctx context.Context, key string) (*domain.PlatformSettings, error) {
	row := s.pool.QueryRow(ctx,
		`SELECT config, updated_at FROM settings WHERE key = $1`, key)

	var configJSON []byte
	var updatedAt pgtype.Timestamptz
	if err := row.Scan(&configJSON, &updatedAt); err != nil {
		return nil, fmt.Errorf("get settings %s: %w", key, err)
	}

	var settings domain.PlatformSettings
	if len(configJSON) > 0 {
		if err := json.Unmarshal(configJSON, &settings); err != nil {
			return nil, fmt.Errorf("unmarshal settings: %w", err)
		}
	}
	settings.UpdatedAt = pgTime(updatedAt)
	return &settings, nil
}

// SaveSettings upserts the platform settings for the given key.
func (s *Store) SaveSettings(ctx context.Context, key string, settings *domain.PlatformSettings) error {
	configJSON, err := json.Marshal(settings)
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}

	_, err = s.pool.Exec(ctx, `
		INSERT INTO settings (key, config, updated_at) VALUES ($1, $2, now())
		ON CONFLICT (key) DO UPDATE SET config = $2, updated_at = now()
	`, key, configJSON)
	if err != nil {
		return fmt.Errorf("save settings %s: %w", key, err)
	}
	return nil
}
