// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genomes.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGenome = `-- name: CreateGenome :exec
INSERT INTO genomes (id, swarm_name, agent_role, generation, parent_ids, active, genes, fitness)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateGenomeParams struct {
	ID         string          `json:"id"`
	SwarmName  string          `json:"swarm_name"`
	AgentRole  string          `json:"agent_role"`
	Generation int32           `json:"generation"`
	ParentIds  []string        `json:"parent_ids"`
	Active     bool            `json:"active"`
	Genes      json.RawMessage `json:"genes"`
	Fitness    []byte          `json:"fitness"`
}

func (q *Queries) CreateGenome(ctx context.Context, arg CreateGenomeParams) error {
	_, err := q.db.Exec(ctx, createGenome,
		arg.ID,
		arg.SwarmName,
		arg.AgentRole,
		arg.Generation,
		arg.ParentIds,
		arg.Active,
		arg.Genes,
		arg.Fitness,
	)
	return err
}

const deactivateGenomes = `-- name: DeactivateGenomes :exec
UPDATE genomes
SET active = false
WHERE swarm_name = $1 AND agent_role = $2 AND active = true
`

type DeactivateGenomesParams struct {
	SwarmName string `json:"swarm_name"`
	AgentRole string `json:"agent_role"`
}

func (q *Queries) DeactivateGenomes(ctx context.Context, arg DeactivateGenomesParams) error {
	_, err := q.db.Exec(ctx, deactivateGenomes, arg.SwarmName, arg.AgentRole)
	return err
}

const getGenomeByID = `-- name: GetGenomeByID :one
SELECT id, swarm_name, agent_role, generation, parent_ids, active, genes, fitness, created_at
FROM genomes
WHERE id = $1
`

type GetGenomeByIDParams struct {
	ID string `json:"id"`
}

type GetGenomeByIDRow struct {
	ID         string             `json:"id"`
	SwarmName  string             `json:"swarm_name"`
	AgentRole  string             `json:"agent_role"`
	Generation int32              `json:"generation"`
	ParentIds  []string           `json:"parent_ids"`
	Active     bool               `json:"active"`
	Genes      json.RawMessage    `json:"genes"`
	Fitness    []byte             `json:"fitness"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGenomeByID(ctx context.Context, arg GetGenomeByIDParams) (GetGenomeByIDRow, error) {
	row := q.db.QueryRow(ctx, getGenomeByID, arg.ID)
	var i GetGenomeByIDRow
	err := row.Scan(
		&i.ID,
		&i.SwarmName,
		&i.AgentRole,
		&i.Generation,
		&i.ParentIds,
		&i.Active,
		&i.Genes,
		&i.Fitness,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGenomesByRole = `-- name: ListActiveGenomesByRole :many
SELECT id, swarm_name, agent_role, generation, parent_ids, active, genes, fitness, created_at
FROM genomes
WHERE swarm_name = $1 AND agent_role = $2 AND active = true
ORDER BY created_at DESC
`

type ListActiveGenomesByRoleParams struct {
	SwarmName string `json:"swarm_name"`
	AgentRole string `json:"agent_role"`
}

type ListActiveGenomesByRoleRow struct {
	ID         string             `json:"id"`
	SwarmName  string             `json:"swarm_name"`
	AgentRole  string             `json:"agent_role"`
	Generation int32              `json:"generation"`
	ParentIds  []string           `json:"parent_ids"`
	Active     bool               `json:"active"`
	Genes      json.RawMessage    `json:"genes"`
	Fitness    []byte             `json:"fitness"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveGenomesByRole(ctx context.Context, arg ListActiveGenomesByRoleParams) ([]ListActiveGenomesByRoleRow, error) {
	rows, err := q.db.Query(ctx, listActiveGenomesByRole, arg.SwarmName, arg.AgentRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGenomesByRoleRow{}
	for rows.Next() {
		var i ListActiveGenomesByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.SwarmName,
			&i.AgentRole,
			&i.Generation,
			&i.ParentIds,
			&i.Active,
			&i.Genes,
			&i.Fitness,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenomesBySwarm = `-- name: ListGenomesBySwarm :many
SELECT id, swarm_name, agent_role, generation, parent_ids, active, genes, fitness, created_at
FROM genomes
WHERE swarm_name = $1
ORDER BY created_at DESC
`

type ListGenomesBySwarmParams struct {
	SwarmName string `json:"swarm_name"`
}

type ListGenomesBySwarmRow struct {
	ID         string             `json:"id"`
	SwarmName  string             `json:"swarm_name"`
	AgentRole  string             `json:"agent_role"`
	Generation int32              `json:"generation"`
	ParentIds  []string           `json:"parent_ids"`
	Active     bool               `json:"active"`
	Genes      json.RawMessage    `json:"genes"`
	Fitness    []byte             `json:"fitness"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGenomesBySwarm(ctx context.Context, arg ListGenomesBySwarmParams) ([]ListGenomesBySwarmRow, error) {
	rows, err := q.db.Query(ctx, listGenomesBySwarm, arg.SwarmName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenomesBySwarmRow{}
	for rows.Next() {
		var i ListGenomesBySwarmRow
		if err := rows.Scan(
			&i.ID,
			&i.SwarmName,
			&i.AgentRole,
			&i.Generation,
			&i.ParentIds,
			&i.Active,
			&i.Genes,
			&i.Fitness,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenomeFitness = `-- name: UpdateGenomeFitness :execresult
UPDATE genomes SET fitness = $1 WHERE id = $2
`

type UpdateGenomeFitnessParams struct {
	Fitness []byte `json:"fitness"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateGenomeFitness(ctx context.Context, arg UpdateGenomeFitnessParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateGenomeFitness, arg.Fitness, arg.ID)
}
