// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AgentMetric struct {
	Time          pgtype.Timestamptz `json:"time"`
	AgentID       string             `json:"agent_id"`
	ContextUsed   pgtype.Int4        `json:"context_used"`
	QueueDepth    pgtype.Int4        `json:"queue_depth"`
	HealthScore   pgtype.Float4      `json:"health_score"`
	CostSession   pgtype.Numeric     `json:"cost_session"`
	CurrentTaskID pgtype.UUID        `json:"current_task_id"`
}

type AgentSpec struct {
	ID         string          `json:"id"`
	SwarmID    string          `json:"swarm_id"`
	Name       string          `json:"name"`
	Model      string          `json:"model"`
	PolicyName pgtype.Text     `json:"policy_name"`
	Config     json.RawMessage `json:"config"`
}

type AuditEvent struct {
	Time       pgtype.Timestamptz `json:"time"`
	AgentID    string             `json:"agent_id"`
	TaskID     pgtype.UUID        `json:"task_id"`
	Action     string             `json:"action"`
	TokensUsed int32              `json:"tokens_used"`
	CostUsd    float64            `json:"cost_usd"`
	InputHash  pgtype.Text        `json:"input_hash"`
	OutputHash pgtype.Text        `json:"output_hash"`
	PrevHash   pgtype.Text        `json:"prev_hash"`
	EventHash  string             `json:"event_hash"`
	Metadata   []byte             `json:"metadata"`
}

type CostEvent struct {
	Time      pgtype.Timestamptz `json:"time"`
	SwarmName string             `json:"swarm_name"`
	AgentRole string             `json:"agent_role"`
	AgentID   string             `json:"agent_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	TokensIn  int32              `json:"tokens_in"`
	TokensOut int32              `json:"tokens_out"`
	CostUsd   float64            `json:"cost_usd"`
	Model     string             `json:"model"`
}

type CostHourly struct {
	Bucket      interface{} `json:"bucket"`
	SwarmName   string      `json:"swarm_name"`
	AgentRole   string      `json:"agent_role"`
	TotalCost   int64       `json:"total_cost"`
	TotalTokens int64       `json:"total_tokens"`
	TaskCount   int64       `json:"task_count"`
}

type Genome struct {
	ID         string             `json:"id"`
	AgentRole  string             `json:"agent_role"`
	Generation int32              `json:"generation"`
	ParentIds  []string           `json:"parent_ids"`
	Genes      json.RawMessage    `json:"genes"`
	Fitness    []byte             `json:"fitness"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	SwarmName  string             `json:"swarm_name"`
}

type MemoryEmbedding struct {
	ID        string             `json:"id"`
	SwarmName string             `json:"swarm_name"`
	AgentRole pgtype.Text        `json:"agent_role"`
	Content   string             `json:"content"`
	Embedding pgvector.Vector    `json:"embedding"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Policy struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Spec      json.RawMessage    `json:"spec"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Swarm struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Spec      json.RawMessage    `json:"spec"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID              string             `json:"id"`
	SwarmID         pgtype.UUID        `json:"swarm_id"`
	AgentRole       string             `json:"agent_role"`
	AssignedAgentID pgtype.Text        `json:"assigned_agent_id"`
	Input           string             `json:"input"`
	Output          pgtype.Text        `json:"output"`
	Status          string             `json:"status"`
	TokensUsed      int32              `json:"tokens_used"`
	CostUsd         float64            `json:"cost_usd"`
	LatencyMs       pgtype.Int4        `json:"latency_ms"`
	Error           pgtype.Text        `json:"error"`
	TraceID         pgtype.Text        `json:"trace_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}
