// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"
	"encoding/json"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (name, spec)
VALUES ($1, $2)
RETURNING id, name, spec, created_at
`

type CreatePolicyParams struct {
	Name string          `json:"name"`
	Spec json.RawMessage `json:"spec"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy, arg.Name, arg.Spec)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyByName = `-- name: GetPolicyByName :one
SELECT id, name, spec, created_at
FROM policies
WHERE name = $1
`

type GetPolicyByNameParams struct {
	Name string `json:"name"`
}

func (q *Queries) GetPolicyByName(ctx context.Context, arg GetPolicyByNameParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByName, arg.Name)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, spec, created_at
FROM policies
ORDER BY created_at DESC
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Spec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
