// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swarms.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgconn"
)

const createSwarm = `-- name: CreateSwarm :one
INSERT INTO swarms (name, spec, status)
VALUES ($1, $2, $3)
RETURNING id, name, spec, status, created_at, updated_at
`

type CreateSwarmParams struct {
	Name   string          `json:"name"`
	Spec   json.RawMessage `json:"spec"`
	Status string          `json:"status"`
}

func (q *Queries) CreateSwarm(ctx context.Context, arg CreateSwarmParams) (Swarm, error) {
	row := q.db.QueryRow(ctx, createSwarm, arg.Name, arg.Spec, arg.Status)
	var i Swarm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSwarm = `-- name: DeleteSwarm :execresult
DELETE FROM swarms WHERE name = $1
`

type DeleteSwarmParams struct {
	Name string `json:"name"`
}

func (q *Queries) DeleteSwarm(ctx context.Context, arg DeleteSwarmParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteSwarm, arg.Name)
}

const getSwarmByName = `-- name: GetSwarmByName :one
SELECT id, name, spec, status, created_at, updated_at
FROM swarms
WHERE name = $1
`

type GetSwarmByNameParams struct {
	Name string `json:"name"`
}

func (q *Queries) GetSwarmByName(ctx context.Context, arg GetSwarmByNameParams) (Swarm, error) {
	row := q.db.QueryRow(ctx, getSwarmByName, arg.Name)
	var i Swarm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSwarms = `-- name: ListSwarms :many
SELECT id, name, spec, status, created_at, updated_at
FROM swarms
ORDER BY created_at DESC
`

func (q *Queries) ListSwarms(ctx context.Context) ([]Swarm, error) {
	rows, err := q.db.Query(ctx, listSwarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Swarm{}
	for rows.Next() {
		var i Swarm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Spec,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSwarmStatus = `-- name: UpdateSwarmStatus :execresult
UPDATE swarms
SET status = $1, updated_at = now()
WHERE name = $2
`

type UpdateSwarmStatusParams struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

func (q *Queries) UpdateSwarmStatus(ctx context.Context, arg UpdateSwarmStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateSwarmStatus, arg.Status, arg.Name)
}
