// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (swarm_id, agent_role, input, status, metadata)
VALUES (
    (SELECT id FROM swarms WHERE name = $1),
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at
`

type CreateTaskParams struct {
	SwarmName string `json:"swarm_name"`
	AgentRole string `json:"agent_role"`
	Input     string `json:"input"`
	Status    string `json:"status"`
	Metadata  []byte `json:"metadata"`
}

type CreateTaskRow struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.SwarmName,
		arg.AgentRole,
		arg.Input,
		arg.Status,
		arg.Metadata,
	)
	var i CreateTaskRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    t.id,
    s.name AS swarm_name,
    t.agent_role,
    t.assigned_agent_id,
    t.input,
    t.output,
    t.status,
    t.tokens_used,
    t.cost_usd,
    t.latency_ms,
    t.error,
    t.trace_id,
    t.metadata,
    t.created_at,
    t.completed_at
FROM tasks t
JOIN swarms s ON s.id = t.swarm_id
WHERE t.id = $1
`

type GetTaskByIDParams struct {
	ID string `json:"id"`
}

type GetTaskByIDRow struct {
	ID              string             `json:"id"`
	SwarmName       string             `json:"swarm_name"`
	AgentRole       string             `json:"agent_role"`
	AssignedAgentID pgtype.Text        `json:"assigned_agent_id"`
	Input           string             `json:"input"`
	Output          pgtype.Text        `json:"output"`
	Status          string             `json:"status"`
	TokensUsed      int32              `json:"tokens_used"`
	CostUsd         float64            `json:"cost_usd"`
	LatencyMs       pgtype.Int4        `json:"latency_ms"`
	Error           pgtype.Text        `json:"error"`
	TraceID         pgtype.Text        `json:"trace_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.SwarmName,
		&i.AgentRole,
		&i.AssignedAgentID,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.TokensUsed,
		&i.CostUsd,
		&i.LatencyMs,
		&i.Error,
		&i.TraceID,
		&i.Metadata,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTasksBySwarm = `-- name: ListTasksBySwarm :many
SELECT
    t.id,
    s.name AS swarm_name,
    t.agent_role,
    t.assigned_agent_id,
    t.input,
    t.output,
    t.status,
    t.tokens_used,
    t.cost_usd,
    t.latency_ms,
    t.error,
    t.trace_id,
    t.metadata,
    t.created_at,
    t.completed_at
FROM tasks t
JOIN swarms s ON s.id = t.swarm_id
WHERE s.name = $1
ORDER BY t.created_at DESC
`

type ListTasksBySwarmParams struct {
	Name string `json:"name"`
}

type ListTasksBySwarmRow struct {
	ID              string             `json:"id"`
	SwarmName       string             `json:"swarm_name"`
	AgentRole       string             `json:"agent_role"`
	AssignedAgentID pgtype.Text        `json:"assigned_agent_id"`
	Input           string             `json:"input"`
	Output          pgtype.Text        `json:"output"`
	Status          string             `json:"status"`
	TokensUsed      int32              `json:"tokens_used"`
	CostUsd         float64            `json:"cost_usd"`
	LatencyMs       pgtype.Int4        `json:"latency_ms"`
	Error           pgtype.Text        `json:"error"`
	TraceID         pgtype.Text        `json:"trace_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListTasksBySwarm(ctx context.Context, arg ListTasksBySwarmParams) ([]ListTasksBySwarmRow, error) {
	rows, err := q.db.Query(ctx, listTasksBySwarm, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksBySwarmRow{}
	for rows.Next() {
		var i ListTasksBySwarmRow
		if err := rows.Scan(
			&i.ID,
			&i.SwarmName,
			&i.AgentRole,
			&i.AssignedAgentID,
			&i.Input,
			&i.Output,
			&i.Status,
			&i.TokensUsed,
			&i.CostUsd,
			&i.LatencyMs,
			&i.Error,
			&i.TraceID,
			&i.Metadata,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskResult = `-- name: UpdateTaskResult :execresult
UPDATE tasks
SET output = $1,
    tokens_used = $2,
    cost_usd = $3,
    latency_ms = $4,
    error = $5,
    completed_at = $6
WHERE id = $7
`

type UpdateTaskResultParams struct {
	Output      pgtype.Text        `json:"output"`
	TokensUsed  int32              `json:"tokens_used"`
	CostUsd     float64            `json:"cost_usd"`
	LatencyMs   pgtype.Int4        `json:"latency_ms"`
	Error       pgtype.Text        `json:"error"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          string             `json:"id"`
}

func (q *Queries) UpdateTaskResult(ctx context.Context, arg UpdateTaskResultParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTaskResult,
		arg.Output,
		arg.TokensUsed,
		arg.CostUsd,
		arg.LatencyMs,
		arg.Error,
		arg.CompletedAt,
		arg.ID,
	)
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execresult
UPDATE tasks
SET status = $1, assigned_agent_id = $2
WHERE id = $3
`

type UpdateTaskStatusParams struct {
	Status          string      `json:"status"`
	AssignedAgentID pgtype.Text `json:"assigned_agent_id"`
	ID              string      `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTaskStatus, arg.Status, arg.AssignedAgentID, arg.ID)
}

const updateTaskStatusOnly = `-- name: UpdateTaskStatusOnly :execresult
UPDATE tasks
SET status = $1
WHERE id = $2
`

type UpdateTaskStatusOnlyParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatusOnly(ctx context.Context, arg UpdateTaskStatusOnlyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTaskStatusOnly, arg.Status, arg.ID)
}
