apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs5224-dev
resources:
  - ../../base
images:
  - name: ghcr.io/your-org/cs5224-web
    newTag: dev
  - name: ghcr.io/your-org/cs5224-py-api
    newTag: dev
  - name: ghcr.io/your-org/cs5224-go-api
    newTag: dev
